### ISSUE TITLE
implement database

### ISSUE THREAD

**Issue by The-One-and-only-Captain** [kinoticketing/ui#8]
currently, all movies of the omdb database get displayed. it would be better if only movies would be shown which have a designated screening in the cinema. for that we need database entries and connection.

A Database has to be added in order to make the following possible:
- Persisting Customer Accounts
- Persisting Admin Accounts
- Persisting the Cinema halls
- Persisting Movie Screenings
- Persisting Tickets

tasks:
- [x] database connection
- [x] enter movies into the database (through admin page)
- [x] load movies from our database, not from omdb (in movies page #10 )

**Comment by okso-hub** [comment]
already done in #11
